name: Build

on:
  push:
  pull_request:

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact phone-libre-arm64-v8a-debug.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-arm64-v8a-debug.apk
          path: ./app/phone/build/outputs/apk/libre/debug/phone-libre-arm64-v8a-debug.apk
 